# Generated by Django 5.2.3 on 2025-08-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
