# Generated by Django 5.2.3 on 2025-08-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_app', '0002_remove_perfilusuario_empresa_remove_proyecto_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='piezas_totales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
