# Generated by Django 5.2.3 on 2025-09-02 17:32

import calidad_app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_app', '0003_proyecto_piezas_totales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-fecha', 'id_lote'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-creado', 'nombre'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='fecha_registro',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='lote',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puesto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='analisis_espectrometrico',
            field=models.FileField(blank=True, null=True, upload_to=calidad_app.models.lot_upload_path),
        ),
        migrations.AlterField(
            model_name='lote',
            name='evidencia_fotografica',
            field=models.FileField(blank=True, null=True, upload_to=calidad_app.models.lot_upload_path),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id_lote',
            field=models.CharField(help_text='Ejemplo: 00001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero_partes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='plano_original',
            field=models.FileField(blank=True, null=True, upload_to=calidad_app.models.lot_upload_path),
        ),
        migrations.AlterField(
            model_name='lote',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='calidad_app.proyecto'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='prueba_dureza',
            field=models.FileField(blank=True, null=True, upload_to=calidad_app.models.lot_upload_path),
        ),
        migrations.AlterField(
            model_name='lote',
            name='prueba_tension',
            field=models.FileField(blank=True, null=True, upload_to=calidad_app.models.lot_upload_path),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tolerancia_geometrica',
            field=models.FileField(blank=True, null=True, upload_to=calidad_app.models.lot_upload_path),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='piezas_totales',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(help_text="Nombre del campo de archivo en Lote, p.ej. 'prueba_dureza'", max_length=50)),
                ('accion', models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('REPLACE', 'REPLACE')], max_length=10)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='calidad_app.lote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha'],
            },
        ),
    ]
