# Generated by Django 5.2.3 on 2025-09-02 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_app', '0004_alter_lote_options_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_subidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
