# Generated by Django 5.2.3 on 2025-09-03 16:25

import calidad_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_app', '0005_lote_subido_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='prueba_dureza',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='prueba_tension',
        ),
        migrations.AddField(
            model_name='lote',
            name='pruebas_mecanicas',
            field=models.FileField(blank=True, help_text='Documento único con dureza y tensión', null=True, upload_to=calidad_app.models.lot_upload_path),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='campo',
            field=models.CharField(help_text="Nombre del campo de archivo (p.ej., 'pruebas_mecanicas')", max_length=50),
        ),
    ]
